<?php
/**
 * Copyright © Qliro AB. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Qliro\QliroOne\Block\Checkout\Success $block */
?>

<div class="success-wrapper">
    <?php if ($block->getIncrementId()): ?>
        <p><?= $block->escapeHtml(__('Order has successfully been placed. Order ID: #%1', $block->getIncrementId())) ?></p>
    <?php endif; ?>
    <div class="qliroone-checkout-success">
        <?php if ($snippet = $block->getSuccessHtmlSnippet()): ?>
            <?php /* @noEscape */ echo $snippet; ?>
        <?php else: ?>
            <div class="js-success-header">
                <?php echo $block->escapeHtml(__('Order has successfully been placed. Order ID: #%1', $block->getIncrementId())); ?>
            </div>
        <?php endif; ?>
    </div>
</div>
